language: ruby
sudo: required
rvm:
  - 2.6.3
services:
  - mysql
before_install:
  - gem update --system
  - gem install bundler
  -  chmod +x ./scripts/* #thanks https://medium.com/@psaunders
before_script:
  - export TZ=Europe/Berlin
  - mysql -e 'create database idb_test;'
  - mv config-example config
  - echo "InfrastructureDb::Application.config.secret_key_base = ('a' * 30)" > config/initializers/secret_token.rb
  - bundle exec rake db:migrate
