version: '3.4'

services:
  app: 
    image: idb:latest
    depends_on:
      - database
      - redis
      - sidekiq
    ports: 
      - "8080:80"
    env_file: docker/idb.env
    command: apachectl -D FOREGROUND

  database:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    env_file: docker/mysql.env

  redis:
    image: redis:6.0.4

  sidekiq:
    image: idb:latest
    depends_on:
      - redis
      - database
    env_file: docker/idb.env
    command: /usr/local/rvm/bin/bootup_sidekiq
