version: '3.4'

services:
  app: 
    image: idb:latest
    depends_on:
      - database
      - redis
    ports: 
      - "8080:80"
    env_file: docker/idb.env
    environment:
      RAILS_ENV: production

  database:
    image: mysql:8.0.20
    volumes:
      - ./docker/mysql:/var/lib/mysql
    env_file: docker/mysql.env

  redis:
    image: redis:6.0.4
