default: &default
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['MYSQL_NAME'] %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  port: <%= ENV['MYSQL_PORT'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  pool: 30

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

