version: '3.4'

services:
  app: 
    image: idb:latest
    depends_on:
      - database
      - redis
      - sidekiq
      - ldap
    ports: 
      - "8080:80"
    env_file: runtime/environments/idb.env
    command: bash -l -c docker/build/scripts/idb.sh

  database:
    image: mysql:5.7
    volumes:
      - ./runtime/data/mysql:/var/lib/mysql
    env_file: runtime/environments/mysql.env

  redis:
    image: redis:6.0.4

  sidekiq:
    image: idb:latest
    depends_on:
      - redis
      - database
    env_file: runtime/environments/idb.env
    command: /bin/bash -l -c docker/build/scripts/sidekiq.sh

  ldap:
    image: osixia/openldap:1.4.0
    env_file: runtime/environments/ldap.env
    volumes:
      - ./runtime/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    command: --copy-service
