version: '3.4'

services:
  app: 
    image: idb:latest
    depends_on:
      - database
      - redis
      - sidekiq
    ports: 
      - "8080:80"
    env_file: idb.env
    command: apachectl -D FOREGROUND

  database:
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
    env_file: mysql.env

  redis:
    image: redis:6.0.4

  sidekiq:
    image: idb:latest
    depends_on:
      - redis
      - database
    env_file: idb.env
    command: /bin/bash -l -c "bundle exec sidekiq"
